# Generated by Django 5.1.15 on 2026-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moviesession',
            index=models.Index(fields=['show_time'], name='cinema_movi_show_ti_234542_idx'),
        ),
    ]
