# Generated by Django 5.1.15 on 2026-07-18 12:07

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to=cinema.models.movie_image_file_path),
        ),
    ]
