# Generated by Django 5.1.13 on 2025-10-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_movie_title'),
        ('cinema', '0003_alter_movie_title_unique'),
    ]

    operations = [
    ]
